name: Authenticator
version: '${project.version}'
main: com.github.tezvn.authenticator.impl.AuthenticatorPluginImpl
api-version: 1.16
depend:
  - AuthMe
  - floodgate
commands:
  taomatkhaucap2:
    usage: /taomatkhaucap2 [mật khẩu] [nhập lại mật khẩu]
  khoiphucmatkhau:
    usage: /khoiphucmatkhau
  matkhaumoi:
    usage: /matkhaumoi [mật khẩu] [nhập lại mật khẩu]
  cleanduplicate:
    usage: /cleanduplicate
permissions:
  authenticator.*:
    default: false
    children:
      authenticator.java.bypass: true
      authenticator.pc.bypass: true
      authenticator.command.cleanduplicate: true
  authenticator.java.bypass:
    default: op
  authenticator.pc.bypass:
    default: false
    description: Allow PC player join server by PE username.
  authenticator.command.cleanduplicate:
    default: op
    description: Allow player to clean duplicate accounts.